on:
  push:
    branches:
      - "Dev"
name: 🚀 Deploy website on push Dev
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME2 }}
        password: ${{ secrets.PASSWORD2 }}
        port: 33